Создает разметку главной страницы и добавляет необходимые изображения
htmlacademy-adaptive/1809473-mishka-24 pull request #2
Opened 2021-11-28 19:48 UTC by x7master

2021-11-28 21:57 UTC, wrgraff requested changes
Я нашел таки до чего докопаться, чтобы не принять задание сразу!
Но ты сделал это сложным =)

2021-11-28 21:57 UTC, wrgraff commented on source/index.html
> +          <img class="main-nav__icon" src="img/menu.svg" width="20" height="14" alt="Открыть меню.">
Это контентная картинка разве? О_о

2021-11-28 21:57 UTC, wrgraff commented on source/index.html
> +          <span class="visually-hidden">Открыть меню</span>
Кстати, если бы мы тут оставляли картинку с атрибутом `alt`, то ей не нужна была бы подпись. Ведь текстовым контентом ссылки стал бы `alt`

2021-11-28 21:57 UTC, wrgraff commented on source/index.html
> +            <a class="user-list__link" href="#">Бесплатная доставка по России</a>
А это и не ссылка вовсе

2021-11-28 21:57 UTC, wrgraff commented on source/index.html
> +          </li>
Рискнешь делать это одним списком?
Тут еще вопрос, а есть ли смысл. Потому что первые 2 пункта — это часть списка страниц. А вторые — ссылки на акционные страницы каталога, видимо. Не сказать, что прям очень хочется в один список их складывать

2021-11-28 21:57 UTC, wrgraff commented on source/index.html
> +        <h2 class="promo__title">Милые штуки ручной работы для дома</h2>
А как это отражает смысл содержания данной секции?

2021-11-28 21:57 UTC, wrgraff commented on source/index.html
> +              <img class="category-item__icon" src="img/interior.svg" width="40" height="62" alt="Настольная лампа.">
Ты чего вдруг декоративные картинки стал ставить в разметку то?

2021-11-28 21:57 UTC, wrgraff commented on source/index.html
> +          </li>
Не очень понятно, есть ли здесь какой-то профит от выделения отдельного блока `category-item`.
Есть ощущение, что и так было бы норм:
```suggestion
          <li class="category-list__item">
            <a class="category-list__link" href="#">
              <p class="category-list__text">Детские игрушки</p>
              <img class="category-list__icon" src="img/toy.svg" width="60" height="60" alt="Кубик Лего.">
            </a>
          </li>
```

А если иконки через стили поставить, то и еще проще будет

2021-11-28 21:57 UTC, wrgraff commented on source/index.html
> +        <span class="featured__promo">Товар недели</span>
Может, наоборот товар недели — это заголовок. Логично же! =)

А еще мне нравится здесь делать заголовок, который читается так: "Товар недели: вязаные корзинки".
Очень понятно и доступно получается

2021-11-28 21:57 UTC, wrgraff commented on source/index.html
> +        <a class="featured__order-link button button--ghost" href="catalog.html">ЗАКАЗАТЬ</a>
Не уверен, что ссылка в этой кнопке на каталог ведет.
Она модалку открывает с добавлением в корзину и выбором размера.
Возможно, это могла бы быть ссылка на товар (может, там прямо на странице выбор размера есть). Но у нас такой страницы нет в макете (но потенциально есть).

2021-11-28 21:57 UTC, wrgraff commented on source/index.html
> +            <p class="advantages-list__text">Экологически<br>чистые материалы</p>
Можно конечно и без параграфов, сам по себе `<li>` тоже контейнер для текста

2021-11-28 21:57 UTC, wrgraff commented on source/index.html
> +            </blockquote>
Подобное использование цитат не совсем верно (или совсем не верно?).
`<cite>` — это название произведения, а не имя автора. И оно не используется внутри `<blockquote>`, так как в этом теге должен быть только цитируемый текст (что логично).

Если очень хочется связать цитату и автора, то стоит использовать тег `<figure>`:

```html
<figure>
  <blockquote>
    <p>Главное, в этом году у нас будет прекрасный чемпион</p>
  </blockquote>
  <figcaption>Ален Прост</figcaption>
</figure>
```

2021-11-28 21:57 UTC, wrgraff commented on source/index.html
> +          <button class="reviews__toggle-left" type="button">
Эти кнопки почти идентичны, разница только в направлении стрелок.
Это разные элементы или один, но в разных видах?

2021-11-28 21:57 UTC, wrgraff commented on source/index.html
> +        <a class="reviews__link button button--ghost" href="#">Написать</a>
Странно, что для `reviews` это `link`, а в целом — `button`.
Так как БЭМ у нас отвечает за представление в интерфейсе, то логично, что кнопка будет и там, и там.
Есть в разметке и еще подобные случаи

2021-11-28 21:57 UTC, wrgraff commented on source/index.html
> +      <h2 class="page-modal__title">Добавить <br>в корзину</h2>
Давай договоримся пока не использовать `<br>`.

Дело в том, что форматированный текст ведет себя иначе, создавая ложное впечатление о своей ширине. А нам на этапе сеток нужно будет убедиться, что он подстраивается под сетку вне зависимости от форматирования. Может выйти и так, что если переносы убрать, то сетка совсем развалится.

Мы потом сможем поставить переносы, если это будет нужно (после модуля сеток).

2021-11-28 21:57 UTC, wrgraff commented on source/index.html
> +        <ul class="page-modal__list modal-list">
Правильно ли считать, что это именно "список модального окна"?
Или все же это как элемент — список в модальном окне (хотя, визуально и тут не список), а как блок — это выбор размеров товара?

2021-11-28 21:57 UTC, wrgraff commented on source/index.html
> +            <label class="modal-list__label" for="modal-size-small"><span class="visually-hidden">Размер: </span>S</label>
Кажется, по заголовку понятно, что речь про размер =)

2021-11-28 21:57 UTC, wrgraff commented on source/index.html
> +            <label class="modal-list__label" for="modal-size-medium"><span class="visually-hidden">Размер: </span>M</label>
Так было бы читаемее, кажется
```suggestion
            <label class="modal-list__label" for="modal-size-medium">
              <span class="visually-hidden">Размер: </span>
              M
            </label>
```

2021-11-29 19:00 UTC, x7master commented on source/index.html
> +          <img class="main-nav__icon" src="img/menu.svg" width="20" height="14" alt="Открыть меню.">
я сначала хотел заинлайнить svg, потом подумал, что не нужно менять состояние по стайлгайду и почему-то оставил такой вариант. а потом вообще про свг спрайты почитал... но пока просто уберем

2021-11-29 19:00 UTC, x7master commented on source/index.html
> +          <span class="visually-hidden">Открыть меню</span>
согласен

2021-11-29 19:02 UTC, x7master commented on source/index.html
> +            <a class="user-list__link" href="#">Бесплатная доставка по России</a>
вот я бы поспорил на самом деле) я бы сделал ссылка на страницу с условиями доставки, но в макете нет такого, так что ок

2021-11-29 19:15 UTC, x7master commented on source/index.html
> +          </li>
дерзну :D

2021-11-29 19:26 UTC, x7master commented on source/index.html
> +        <h2 class="promo__title">Милые штуки ручной работы для дома</h2>
да прямо отражает, промо материал, промо о чем? о милых штуках для дома, а конкретно "предметы для интерьера" и "детские игрушки". сделать это промо текст и вкрячить hidden заголовок "Промо" - ну не знаю.

2021-11-29 19:32 UTC, x7master commented on source/index.html
> +              <img class="category-item__icon" src="img/interior.svg" width="40" height="62" alt="Настольная лампа.">
заинлайнил свг, т.к. у нас потом будет меняться его состояние

2021-11-29 19:36 UTC, x7master commented on source/index.html
> +          </li>
ок

2021-11-29 19:39 UTC, x7master commented on source/index.html
> +        <span class="featured__promo">Товар недели</span>
я художник, я так вижу)

2021-11-29 19:43 UTC, x7master commented on source/index.html
> +            <p class="advantages-list__text">Экологически<br>чистые материалы</p>
я пока оставлю, на стилизации посмотрим

2021-11-29 19:45 UTC, x7master commented on source/index.html
> +        <a class="featured__order-link button button--ghost" href="catalog.html">ЗАКАЗАТЬ</a>
согласен

2021-11-29 19:51 UTC, x7master commented on source/index.html
> +            </blockquote>
ok

2021-11-29 19:57 UTC, x7master commented on source/index.html
> +        <a class="reviews__link button button--ghost" href="#">Написать</a>
факир был пьян и баттон не удался

2021-11-29 19:58 UTC, x7master commented on source/index.html
> +      <h2 class="page-modal__title">Добавить <br>в корзину</h2>
ок

2021-11-29 20:06 UTC, x7master commented on source/index.html
> +        <ul class="page-modal__list modal-list">
ну наверное все же page-modal__list

2021-11-29 20:07 UTC, x7master commented on source/index.html
> +            <label class="modal-list__label" for="modal-size-small"><span class="visually-hidden">Размер: </span>S</label>
ну да, тогда они вообще тут не нужны

2021-11-29 20:07 UTC, x7master commented on source/index.html
> +            <label class="modal-list__label" for="modal-size-medium"><span class="visually-hidden">Размер: </span>M</label>
нет спана - нет проблем

2021-11-29 21:44 UTC, wrgraff commented on source/index.html
> +        <h2 class="promo__title">Милые штуки ручной работы для дома</h2>
Так по такой логике можно и про весь сайт сказать, что этот заголовок отражает его содержание (на самом деле тоже не очень).
А данную секцию вот как раз не очень. Ты сопоставляешь как-то странно: сначала берешь контент, а потом проверяешь подходит ли он заголовку. Может и подходит, но работать то это будет не так. Навигация по заголовкам просто скажет вот эту фразу "милые штучки для дома" и по нему уже надо будет догадаться -- что внутри этого блока. Неужели ты подумаешь, что это заголовок для каких-то разделов каталога?

"Промо" тоже подходит не очень.

2021-11-29 21:45 UTC, wrgraff commented on source/index.html
> +            <a class="user-list__link" href="#">Бесплатная доставка по России</a>
Нет указаний на то, что это интерактивный элемент. Все другие элементы хэдера при этом в стайлгайде описаны по поведению

2021-11-29 21:46 UTC, wrgraff commented on source/index.html
> +          <img class="main-nav__icon" src="img/menu.svg" width="20" height="14" alt="Открыть меню.">
До спрайтов еще дожить надо...

2021-11-29 21:46 UTC, wrgraff approved these changes

2021-11-29 21:46 UTC, merged