Module2 task2
htmlacademy-adaptive/1809473-mishka-24 pull request #3
Opened 2021-12-01 20:51 UTC by x7master

2021-12-02 00:11 UTC, wrgraff requested changes
Посмотри [на примере разбора формы Барбершопа](https://youtube.com/playlist?list=PL6xpnt2woRKk0btmfzM2oR6-ste7wZUWm) какое количество блоков там можно выделить

2021-12-02 00:11 UTC, wrgraff commented on source/form.html
> +                <label class="order__label--checkbox">
Создать всю разницу между этими инпутам-контролами (как чекбокс и радио) и инпутами-полями (с текстом типа имя, телефон) за счет одного лишь модификатора — очень плохая затея.
Во-первых, они не похожи.
Во-вторых, нужно в одном из них только через модификатор нарисовать чекбокс, описать его состояния при взаимодействии, состояние отмеченного и нет... Это много логики для вещи, которая призвана решать примерно такие задачи: "_так, вот это 5 кнопок, а вот одна из них — красная!_"

2021-12-03 19:55 UTC, x7master commented on source/catalog.html
> +            <a class="site-list__link" href="catalog.html">Каталог товаров</a>
Убираю, исправил

2021-12-03 19:56 UTC, x7master commented on source/form.html
> +      <section class="page-main__header">
согласен, убрал

2021-12-03 20:33 UTC, x7master commented on source/form.html
> +                <label class="order__label--checkbox">
согласен

2021-12-03 20:33 UTC, x7master commented on source/form.html
> +              </li>
переделал

2021-12-03 20:34 UTC, x7master commented on source/form.html
> +              </li>
да, пожалуй я переборщил

2021-12-03 20:35 UTC, x7master commented on source/form.html
> +          <fieldset class="order__category--type">
а ведь проверял, но решил отправить, спасибо за видео!

2021-12-03 20:44 UTC, x7master commented on source/catalog.html
> +          <li class="catalog__item">
действительно!

2021-12-03 20:45 UTC, x7master commented on source/catalog.html
> +            <h3 class="catalog__title">Зайчик-попрыгайчик</h3>
читал, но, каюсь, в полночь уже не вспомнилось =(

2021-12-03 20:52 UTC, x7master commented on source/catalog.html
> +            <button class="catalog__button" type="button">
Принято

2021-12-03 20:53 UTC, x7master commented on source/catalog.html
> +        <a class="production__order-link button--ghost" href="form.html">Сделать заказ</a>
принято

2021-12-04 11:57 UTC, wrgraff approved these changes
Есть пара моментов, но давай их уже в следующем задании исправим

2021-12-04 11:57 UTC, wrgraff commented on source/catalog.html
> +            <a class="site-list__link" href="#">Каталог товаров</a>
Но это не убранная ссылка. Это — заглушка вместо адреса, который мы не знаем.
Нужно или убирать ссылки на текущую страницу, убирая атрибут `href`, либо оставлять нормальную ссылку с адресом

2021-12-04 11:57 UTC, wrgraff commented on source/form.html
> +        <fieldset class="order-form__group form-group form-group--mail">
А почему телефон и почта в разных группах полей?
Как-то не очень логично выходит. Да, выглядят они как до этого группы полей, но по смыслу хорошо бы их объединить в одну группу контактов. А вот как это оформить потом... Это надо будет подумать

2021-12-04 11:57 UTC, merged