Введение препроцессора, стилизация шрифтов, добавление фоновых
htmlacademy-adaptive/1809473-mishka-24 pull request #4
Opened 2021-12-18 08:44 UTC by x7master

2021-12-18 10:56 UTC, wrgraff requested changes
Молодец, надо только несколько деталей подправить

2021-12-18 10:56 UTC, wrgraff commented on source/index.html
> +            <a class="category-list__link category-list__link--first" href="#">
Нет никакого смысла использовать классы типа `something-1`, `something-2`, и так далее.

Если тебе нужно стилизовать что-то по порядковому номеру, то в CSS есть такие вещи, как `:first-child`, `:nth-child`, `:nth-of-type` и прочие. Они придуманы специально чтобы выбирать элемент по порядку. И если их в разметке перемешать, то они все равно будут выбирать по порядку.

Если же необходимо дать стили элементу так, чтобы при перемешивании стили оставались при нём (например, иконка, которая относится непосредственно к элементу), то нужен класс, отражающий суть этого изменения, а не порядковый номер.

2021-12-18 10:56 UTC, wrgraff commented on source/sass/style.scss
> +//fonts
Почему `fonts`?
Там же переменные, миксины и всякое разное, не только к шрифтам относящееся

2021-12-18 10:56 UTC, wrgraff commented on source/sass/style.scss
> +@import "blocks/category-list";
Надо или писать расширение файла, или не писать

2021-12-18 10:56 UTC, wrgraff commented on source/sass/style.scss
> +@import "global/mixins.scss";
Вообще, переменные могут понадобиться и внутри глобального или шрифтового файла, логичнее их подключать в первую очередь

2021-12-18 10:56 UTC, wrgraff commented on source/sass/global/variables.scss
> +$semi-grey: #f1f1f1;
Проблема переменных с таким именованием в том, что на этом этапе мне вот уже непонятно что такое `$semi-grey` и должен ли он быть светлее или темнее `$light-grey`.
А серых цветов в проекте еще довольно много.
Потому и рекомендую заводить палитру с цифровым значением. Для веба это очень привычная схема, например шрифты даже на нативном уровне имеют вес от 100 до 900.

2021-12-18 10:56 UTC, wrgraff commented on source/sass/blocks/user-list.scss
> +    background-image: url("../../img/search.svg");
Неправильный путь к файлу. Препроцессор не умеет при сборке переписывать пути к картинкам. Это обычная статическая строка. Поэтому нам нужно писать путь исходя из того, где находится наш скомпилированный css-файл.

У нас директория `img` находится обычно рядом с директорией `css`, а значит нужно один раз выйти из директории(`../`) и зайти в картинки.

> Почему же при всем при этом картинки работают?
Потому, что лишние выходы на уровень выше не срабатывают, так как мы сразу попадаем в корневую директорию. Однако, если мы сделаем тоже самое на сервере с другими настройками, то будет проблема. Например, попробуй опубликовать свой пул-реквест в интерфейсе проверки задания (прямо в интерфейсе Академии есть такая кнопка)

2021-12-18 10:56 UTC, wrgraff commented on source/sass/global/fonts.scss
> +  src: url("../../fonts/opensans.woff2") format("woff2"), url("/source/fonts/opensans.woff") format("woff");
А как ты умудрился указать путь в одно и тоже место двумя разными способами?
При чем, оба неправильные (аналогично картинкам все должно работать)

2021-12-18 10:56 UTC, wrgraff commented on source/sass/blocks/user-list.scss
> +    background-repeat: no-repeat;
Можно вынести правило повторения фона в сам класс `.user-list__link` и не писать его дважды

2021-12-18 10:56 UTC, wrgraff commented on source/sass/blocks/reviews.scss
> +  font-weight: normal;
Немного странно, что где-то толщина в цифрах, а где-то ключевыми словами.
Лучше писать единообразно.

2021-12-18 10:56 UTC, wrgraff commented on source/sass/blocks/reviews.scss
> +  font-weight: normal;
Вообще, указывать вес текста, если он такой по умолчанию и / или наследуется — немного спорно.
Так можно дойти до того, что мы все свойства должны будем переписать, чтобы нигде не было значений по умолчанию.

Да, получается так, что настоящей независимости в верстке не добиться.

2021-12-18 10:56 UTC, wrgraff commented on source/sass/blocks/advantages-list.scss
> +    background-repeat: no-repeat;
Не надоело писать одно и тоже 6 раз то? )
Можно и один раз написать было...

2021-12-18 10:56 UTC, wrgraff commented on source/sass/global/mixins.scss
> +}
Не уверен в том, что поддержка миксинов будет того стоить, но по крайней мере они используются логично.

2021-12-19 09:33 UTC, x7master commented on source/index.html
> +            <a class="category-list__link category-list__link--first" href="#">
Сделаем пока interior и toys, потом уберем если освободится...

2021-12-19 09:34 UTC, x7master commented on source/sass/style.scss
> +//fonts
приберемся немного

2021-12-19 09:35 UTC, x7master commented on source/sass/style.scss
> +@import "blocks/category-list";
будем писать для точности

2021-12-19 09:35 UTC, x7master commented on source/sass/style.scss
> +@import "global/mixins.scss";
согалсен

2021-12-19 10:00 UTC, x7master commented on source/sass/global/variables.scss
> +$semi-grey: #f1f1f1;
всё-таки я проследил некую систему...

2021-12-19 10:08 UTC, x7master commented on source/sass/blocks/user-list.scss
> +    background-image: url("../../img/search.svg");
меня сбила работа vscode с путями и собственно недостаток понимания настроек работы сборщика

2021-12-19 10:08 UTC, x7master commented on source/sass/global/fonts.scss
> +  src: url("../../fonts/opensans.woff2") format("woff2"), url("/source/fonts/opensans.woff") format("woff");
а тут факир был явно пьян и фокус не удался

2021-12-19 10:09 UTC, x7master commented on source/sass/blocks/user-list.scss
> +    background-repeat: no-repeat;
согласен

2021-12-19 10:12 UTC, x7master commented on source/sass/blocks/reviews.scss
> +  font-weight: normal;
ctrl+c ctrl+v до добра не доведет...

2021-12-19 10:13 UTC, x7master commented on source/sass/blocks/reviews.scss
> +  font-weight: normal;
грустно одним словом

2021-12-19 10:14 UTC, x7master commented on source/sass/blocks/advantages-list.scss
> +    background-repeat: no-repeat;
так я один раз написал и скопировал, а думать то зачем?)

2021-12-19 10:14 UTC, x7master commented on source/sass/global/mixins.scss
> +}
хотелось бы больше их...

2021-12-19 15:37 UTC, wrgraff commented on source/index.html
> +            <a class="category-list__link category-list__link--first" href="#">
Кто освободится?

2021-12-19 15:42 UTC, wrgraff commented on source/sass/style.scss
> +//variables
А то без подписей не понятно что `global/variables.scss` — это variables =)

2021-12-19 15:42 UTC, wrgraff commented on source/sass/global/variables.scss
> +$background-color: #f1f1f1;
Посмотрим, как ты дальше с этой системой будешь жить и как в нее впишется 12 оттенков серого и 8 оттенков зеленого этого макета ))
Ну если получится, то хорошо

2021-12-19 15:42 UTC, wrgraff commented on source/sass/global/fonts.scss
> +  src: url("../fonts/opensansbold.woff2") format("woff2"), url("../fonts/opensansbold.woff") format("woff");
Зато теперь понял, что сборщик никакой магии не делает и все надо ручками править ))

2021-12-19 15:42 UTC, wrgraff commented on source/sass/blocks/reviews.scss
> +  font-weight: normal;
В общем да )

2021-12-19 15:43 UTC, wrgraff commented on source/sass/global/mixins.scss
> +}
Не, хотелось бы меньше )

2021-12-19 15:43 UTC, wrgraff commented on source/sass/blocks/advantages-list.scss
> +    background-repeat: no-repeat;
Правильно, не надо думать — это пустое )

2021-12-19 15:44 UTC, wrgraff approved these changes

2021-12-19 15:44 UTC, merged